version: 2

sphinx:
  configuration: src/conf.py

python:
  install:
  - requirements: requirements.txt

build  :
  os: ubuntu-22.04
  tools:
    python: "3.9"

  commands:
    - git submodule update --init
    - python -m sphinx -T -E -b html -d _build/doctrees -D language=en . _build/html
